<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="6" failed="1" total="9" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="63968" started-at="2017-03-31T13:04:01Z" finished-at="2017-03-31T13:05:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="63968" started-at="2017-03-31T13:04:01Z" finished-at="2017-03-31T13:05:05Z">
      <class name="main.java.test.DRMMainTests.iOSDRMTest">
        <test-method status="PASS" signature="Setup()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8]" name="Setup" is-config="true" duration-ms="25725" started-at="2017-03-31T14:04:01Z" finished-at="2017-03-31T14:04:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method status="PASS" signature="openDRMApp()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8]" name="openDRMApp" duration-ms="1636" started-at="2017-03-31T14:04:27Z" finished-at="2017-03-31T14:04:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openDRMApp -->
        <test-method status="PASS" signature="vpid_Download()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8]" name="vpid_Download" duration-ms="26312" started-at="2017-03-31T14:04:28Z" depends-on-methods="main.java.test.DRMMainTests.iOSDRMTest.openDRMApp" finished-at="2017-03-31T14:04:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- vpid_Download -->
        <test-method status="FAIL" signature="check_Vpid()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8]" name="check_Vpid" duration-ms="10274" started-at="2017-03-31T14:04:55Z" depends-on-methods="main.java.test.DRMMainTests.iOSDRMTest.vpid_Download" finished-at="2017-03-31T14:05:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [In Progress - 0.3%] but found [In Progress]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [In Progress - 0.3%] but found [In Progress]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at main.java.test.DRMMainTests.iOSDRMTest.check_Vpid(iOSDRMTest.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- check_Vpid -->
        <test-method status="SKIP" signature="turnWiFi_Off()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8]" name="turnWiFi_Off" duration-ms="0" started-at="2017-03-31T14:05:05Z" depends-on-methods="main.java.test.DRMMainTests.iOSDRMTest.check_Vpid" finished-at="2017-03-31T14:05:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method iOSDRMTest.turnWiFi_Off()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method iOSDRMTest.turnWiFi_Off()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- turnWiFi_Off -->
        <test-method status="SKIP" signature="turnWiFi_ON()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8]" name="turnWiFi_ON" duration-ms="0" started-at="2017-03-31T14:05:05Z" depends-on-methods="main.java.test.DRMMainTests.iOSDRMTest.turnWiFi_Off" finished-at="2017-03-31T14:05:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method iOSDRMTest.turnWiFi_ON()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method iOSDRMTest.turnWiFi_ON()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- turnWiFi_ON -->
        <test-method status="SKIP" signature="downloadPause()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8]" name="downloadPause" duration-ms="0" started-at="2017-03-31T14:05:05Z" depends-on-methods="main.java.test.DRMMainTests.iOSDRMTest.turnWiFi_ON" finished-at="2017-03-31T14:05:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method iOSDRMTest.downloadPause()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method iOSDRMTest.downloadPause()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- downloadPause -->
        <test-method status="SKIP" signature="downloadResume()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8]" name="downloadResume" duration-ms="0" started-at="2017-03-31T14:05:05Z" depends-on-methods="main.java.test.DRMMainTests.iOSDRMTest.downloadPause" finished-at="2017-03-31T14:05:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method iOSDRMTest.downloadResume()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method iOSDRMTest.downloadResume()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- downloadResume -->
        <test-method status="SKIP" signature="DownloadProgress()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8]" name="DownloadProgress" duration-ms="0" started-at="2017-03-31T14:05:05Z" depends-on-methods="main.java.test.DRMMainTests.iOSDRMTest.downloadResume" finished-at="2017-03-31T14:05:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method iOSDRMTest.DownloadProgress()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method iOSDRMTest.DownloadProgress()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DownloadProgress -->
        <test-method status="SKIP" signature="DownloadComplete()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8]" name="DownloadComplete" duration-ms="0" started-at="2017-03-31T14:05:05Z" depends-on-methods="main.java.test.DRMMainTests.iOSDRMTest.DownloadProgress" finished-at="2017-03-31T14:05:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method iOSDRMTest.DownloadComplete()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method iOSDRMTest.DownloadComplete()[pri:0, instance:main.java.test.DRMMainTests.iOSDRMTest@3159c4b8] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DownloadComplete -->
      </class> <!-- main.java.test.DRMMainTests.iOSDRMTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
